services:
  embedding-service:
    # na razie CPU (bo GPU na RTX 50xx i tak nie przejdzie w TEI 1.8)
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.8
    container_name: embedding-service-srv
    restart: unless-stopped
    ports: ["8580:80"]
    volumes:
      - embedding-srv-data:/data
    environment:
      - MODEL_ID=intfloat/multilingual-e5-base
      # (opcjonalnie) ogranicz wątki, by uniknąć konfliktów blas/mkl:
      - OMP_NUM_THREADS=4
      - MKL_NUM_THREADS=4
    command:
      - --model-id
      - "intfloat/multilingual-e5-base"
      - --auto-truncate
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:80/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  embedding-srv-data: