services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: es
    environment:
      - node.name=es-node
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=elastic
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s -u elastic:elastic http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"'"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  # Multi-platform embedding service
  embedding-service:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.8
    container_name: embedding-service
    volumes:
      - embedding-data:/data
    environment:
      - MODEL_ID=sentence-transformers/all-MiniLM-L6-v2
    ports:
      - "8580:80"
    command:
      - --model-id
      - "sentence-transformers/all-MiniLM-L6-v2"
    depends_on:
      - elasticsearch

  # Ollama service - works on both x86_64 and arm64
  ollama-service:
    image: ollama/ollama:latest
    container_name: ollama-service
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    depends_on:
      - elasticsearch
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434/api/tags || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

volumes:
  elasticsearch-data:
  ollama_data:
  embedding-data:
