import type { HrAbsenceRequest } from '../types/hrAbsenceTypes'

const hrAbsenceRequests: HrAbsenceRequest[] = [
  {
    id: 'absence-ctx-001',
    companyId: 'employment-citronex-it',
    employeeId: 'employee-001',
    employeeName: 'Anna Nowak',
    leaveType: 'annual',
    dateFrom: '2026-08-24',
    dateTo: '2026-08-28',
    days: 5,
    submittedAt: '2026-08-10T08:20:00Z',
    managerName: 'Jan Kowalski',
    status: 'pending',
    requiresPayrollClosure: true,
  },
  {
    id: 'absence-ctx-002',
    companyId: 'employment-citronex-it',
    employeeId: 'employee-002',
    employeeName: 'Marek Wiśniewski',
    leaveType: 'onDemand',
    dateFrom: '2020-02-10',
    dateTo: '2020-02-10',
    days: 1,
    submittedAt: '2020-02-09T14:05:00Z',
    managerName: 'Ewa Zielińska',
    status: 'pending',
    requiresPayrollClosure: false,
  },
  {
    id: 'absence-ctx-003',
    companyId: 'employment-citronex-it',
    employeeId: 'employee-003',
    employeeName: 'Joanna Wójcik',
    leaveType: 'childCare',
    dateFrom: '2026-07-16',
    dateTo: '2026-07-17',
    days: 2,
    submittedAt: '2026-07-02T09:45:00Z',
    managerName: 'Jan Kowalski',
    status: 'approved',
    requiresPayrollClosure: false,
  },
  {
    id: 'absence-ctx-004',
    companyId: 'employment-citronex-it',
    employeeId: 'employee-004',
    employeeName: 'Piotr Kamiński',
    leaveType: 'occasional',
    dateFrom: '2026-09-03',
    dateTo: '2026-09-04',
    days: 2,
    submittedAt: '2026-08-18T11:30:00Z',
    managerName: 'Ewa Zielińska',
    status: 'rejected',
    requiresPayrollClosure: false,
  },
  {
    id: 'absence-ppo-001',
    companyId: 'employment-polskie-pomidory-consultant',
    employeeId: 'employee-101',
    employeeName: 'Katarzyna Lewandowska',
    leaveType: 'annual',
    dateFrom: '2026-08-27',
    dateTo: '2026-09-02',
    days: 5,
    submittedAt: '2026-08-12T07:50:00Z',
    managerName: 'Tomasz Dąbrowski',
    status: 'pending',
    requiresPayrollClosure: true,
  },
  {
    id: 'absence-ppo-002',
    companyId: 'employment-polskie-pomidory-consultant',
    employeeId: 'employee-102',
    employeeName: 'Łukasz Szymański',
    leaveType: 'onDemand',
    dateFrom: '2020-03-12',
    dateTo: '2020-03-12',
    days: 1,
    submittedAt: '2020-03-12T06:10:00Z',
    managerName: 'Tomasz Dąbrowski',
    status: 'pending',
    requiresPayrollClosure: false,
  },
  {
    id: 'absence-ppo-003',
    companyId: 'employment-polskie-pomidory-consultant',
    employeeId: 'employee-103',
    employeeName: 'Natalia Woźniak',
    leaveType: 'occasional',
    dateFrom: '2026-06-05',
    dateTo: '2026-06-05',
    days: 1,
    submittedAt: '2026-05-29T13:15:00Z',
    managerName: 'Monika Kozłowska',
    status: 'approved',
    requiresPayrollClosure: false,
  },
]

export async function getHrAbsenceRequests(): Promise<HrAbsenceRequest[]> {
  await new Promise((resolve) => setTimeout(resolve, 150))
  return structuredClone(hrAbsenceRequests)
}
